Repository isabelrem/2023-Software-Development-Assessment, pull requests merged in 2023-12, with the labels that each got.

#37 Refactor/generate bed
  .gitignore
  PanelSearch/generate_bed.py
  PanelSearch/main.py
Labels: good first issue

#44 41 exon boundaries
  PanelSearch/VV_Request_Parse.py
  PanelSearch/generate_bed.py
Labels: enhancement

#46 Changes made so that 500 and 404 status codes from do not cause an ex…
  PanelSearch/PanelApp_Request_Parse.py
  PanelSearch/VV_Request_Parse.py
  PanelSearch/main.py
Labels: bug
